name: AWS S3 Data Sync To Filebase
on:
  workflow_dispatch:
  push:
  # schedule:
  #   - cron: "0 * * * *" # To run at 0 minute every single hour of every single week
env:
  AWS_S3_BUCKET_NAME: myS3Bucket
  FILEBASE_BUCKET_NAME: myFilebaseBucket

jobs:
  s3sync:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
      - name: Check out the Repo
        uses: actions/checkout@v4.1.5
      - name: Inject Access Keys into Rclone Conf File
        uses: cuchi/jinja2-action@v1.2.2
        with:
          template: rclone-temp.conf
          output_file: rclone-prod.conf
          strict: true
          variables: |
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY}}
            FILEBASE_ACCESS_KEY_ID=${{ secrets.FILEBASE_ACCESS_KEY_ID }}
            FILEBASE_SECRET_ACCESS_KEY=${{ secrets.FILEBASE_SECRET_ACCESS_KEY }}
      - name: Running Rclone Sync Command
        run: |
          rclone sync s3Source:${{ env.AWS_S3_BUCKET_NAME}} filebaseDest:${{ env.FILEBASE_BUCKET_NAME }} --config rclone-prod.conf --auto-confirm
